# Generated by Django 4.2 on 2023-05-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmulti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='type_of_field',
            field=models.CharField(choices=[('general', 'Тип данных не известен'), ('int', 'Число целое'), ('float', 'Число с плавающей точкой'), ('dict', 'Словарь')], default='general', max_length=10),
        ),
    ]
